# Site settings
title: Abhi's Thoughts
header-img: img/home-bg.png
email: abhi.pillai1@gmail.com
copyright_name: abhishekpillai
description: > # this means to ignore newlines until "baseurl:"
  Read my thoughts
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  abhishekpillai
learn_profile: abhishekpillai
email_username: abhi.pillai1@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
